version: '3.8'
services:
  postgresql:
    container_name: db-postgres
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_PASSWORD=postgres
